openapi: 3.0.0
info:
  title: Restapi
  description: |-
   Documentation Restapi
  version: 1.0.0
servers:
  - url: http://localhost:3000
tags:
paths:
components:
  schemas:
  requestBodies:
  securitySchemes: